from analyzers.core.formatter import format_formula


NAME = "Look-and-Say Numbers"
DESCRIPTION = "Self-describing sequence generated by reading the previous term."
REPRESENTATION = "Recursive"
CATEGORY = "Special"
SPECIFICITY = 70
PARENT = "Recursive"
NATURAL_FAMILY = True


# Mathematical Metadata
OEIS = "A005150"

ALIASES = [
    "Conway Sequence",
    "Look and Say Sequence",
]


CLOSED_FORM = False
EVALUATION_METHOD = "Recursive Generation"

FAMILY_TYPE = "Sequence"


TAGS = (
    "Recursive",
    "Self Generating",
    "Combinatorial",
)


TRAITS = {
    "growth": "combinatorial",
    "construction": "recursive",
    "domain": "integers",
}


RELATED = [
    "Recurrence Sequences",
]


DOMAIN = "Integers"
GROWTH = "Combinatorial"


MONOTONIC = True
BOUNDED = False
OSCILLATING = False
PERIODIC = False


FORMULA_TYPE = REPRESENTATION

REQUIRES_PARAMETERS = False

PARAMETER_NAMES = (
)


MIN_TERMS = 5

RECOGNITION_METHOD = "Recursive Generation"
RELIABILITY = "Exact"



def next_term(value):

    digits = str(value)

    result = ""

    count = 1

    for i in range(1, len(digits) + 1):

        if i < len(digits) and digits[i] == digits[i-1]:

            count += 1

        else:

            result += str(count)
            result += digits[i-1]

            count = 1

    return int(result)



def look_and_say(n):

    if n == 1:
        return 1


    value = 1

    for _ in range(2, n + 1):

        value = next_term(value)


    return value



def recognize(sequence):

    if len(sequence) < MIN_TERMS:
        return None


    for index, value in enumerate(sequence, start=1):

        if value != look_and_say(index):

            return None


    return True



def fit(sequence):

    if recognize(sequence) is not True:
        return None

    return {}



def evaluate(parameters, n):

    return look_and_say(n)



def formula(parameters):

    return format_formula(
        "read(previous term)"
    )



def complexity(_):

    return 3



def explain(parameters):

    return [
        "The sequence matches the Look-and-Say recursive generation rule.",
        "Each term is produced by describing the digits of the previous term.",
        "The sequence is generated through self-reference rather than a closed formula."
    ]