TEST_SEQUENCES = [
    {
        "name": "Constant",
        "sequence": [5, 5, 5],
        "type": "Constant",
        "formula": "a(n) = 5",
        "prediction": [5, 5, 5],
        "verified": True
    },
    {
        "name": "Arithmetic",
        "sequence": [2, 5, 8, 11],
        "type": "Arithmetic",
        "formula": "a(n) = 3n - 1",
        "prediction": [14, 17, 20],
        "verified": True
    },
    {
        "name": "Triangular",
        "sequence": [1, 3, 6, 10, 15],
        "type": "Triangular",
        "formula": "a(n) = n(n+1)/2",
        "prediction": [21, 28, 36],
        "verified": True
    },
    {
        "name": "Polynomial (Cubic)",
        "sequence": [0, 11, 46, 117, 236],
        "type": "Polynomial",
        "formula": "a(n) = 2n^3 - 3n + 1",
        "prediction": [415, 666, 1001],
        "verified": True,
    },
    {
        "name": "Geometric (Ratio 3)",
        "sequence": [5, 15, 45, 135, 405],
        "type": "Geometric",
        "formula": "a(n) = 5 · 3^(n-1)",
        "prediction": [1215, 3645, 10935],
        "verified": True,
    },
    {
        "name": "Pentagonal",
        "sequence": [1, 5, 12, 22, 35],
        "type": "Pentagonal",
        "formula": "a(n) = n(3n-1)/2",
        "prediction": [51, 70, 92],
        "verified": True,
    },
    {
        "name": "Fibonacci",
        "sequence": [1, 1, 2, 3, 5, 8],
        "type": "Fibonacci",
        "formula": "a(n) = a(n-1) + a(n-2)",
        "prediction": [13, 21, 34],
        "verified": True,
    },
    {
        "name": "Lucas",
        "sequence": [2, 1, 3, 4, 7, 11],
        "type": "Lucas",
        "formula": "a(n) = a(n-1) + a(n-2)",
        "prediction": [18, 29, 47],
        "verified": True,
    },
    {
        "name": "Pell",
        "sequence": [0, 1, 2, 5, 12, 29],
        "type": "Pell",
        "formula": "a(n) = 2a(n-1) + a(n-2)",
        "prediction": [70, 169, 408],
        "verified": True,
    },
    {
        "name": "Jacobsthal",
        "sequence": [0, 1, 1, 3, 5, 11],
        "type": "Jacobsthal",
        "formula": "a(n) = a(n-1) + 2a(n-2)",
        "prediction": [21, 43, 85],
        "verified": True,
    },
    {
        "name": "Factorial",
        "sequence": [1, 2, 6, 24, 120, 720],
        "type": "Factorial",
        "formula": "a(n) = n!",
        "prediction": [5040, 40320, 362880],
        "verified": True,
    }  
]