# ============================================================
# Collatz Stopping Times
# ============================================================

from analyzers.core.formatter import format_formula


NAME = "Collatz Stopping Times"
DESCRIPTION = "Number of steps required for Collatz convergence."
REPRESENTATION = "Recursive"
CATEGORY = "Special"
SPECIFICITY = 55
PARENT = "Recursive"
NATURAL_FAMILY = True


OEIS = "A006577"

ALIASES = [
    "Total Stopping Time",
]


CLOSED_FORM = False
EVALUATION_METHOD = "Recursive Process"

FAMILY_TYPE = "Sequence"


TAGS = (
    "Recursive",
    "Iterative",
)


TRAITS = {
    "growth": "irregular",
    "construction": "recursive",
    "domain": "integers",
}


RELATED = [
    "Happy Numbers",
]


DOMAIN = "Integers"
GROWTH = "Irregular"


MONOTONIC = None
BOUNDED = False
OSCILLATING = True
PERIODIC = False


FORMULA_TYPE = REPRESENTATION

REQUIRES_PARAMETERS = False

PARAMETER_NAMES = ()

MIN_TERMS = 5

RECOGNITION_METHOD = "Iterative Process"
RELIABILITY = "Exact"


def stopping_time(n):

    steps = 0

    while n != 1:

        if n % 2 == 0:
            n //= 2

        else:
            n = 3 * n + 1

        steps += 1

    return steps


def recognize(sequence):

    expected = [
        stopping_time(n)
        for n in range(1, len(sequence) + 1)
    ]

    return sequence == expected


def fit(sequence):

    if recognize(sequence):
        return {}

    return None


def evaluate(parameters, n):

    return stopping_time(n)


def formula(parameters):

    return format_formula(
        "Iterative Collatz transformation"
    )


def complexity(_):

    return 3


def explain(parameters):

    return [
        "Each term records the number of Collatz iterations required to reach 1.",
        "The sequence is generated through recursive integer transformation.",
    ]


# ============================================================
# Happy Numbers
# ============================================================

from analyzers.core.formatter import format_formula


NAME = "Happy Numbers"
DESCRIPTION = "Numbers whose digit-square process eventually reaches 1."
REPRESENTATION = "Recursive"
CATEGORY = "Special"
SPECIFICITY = 55
PARENT = "Recursive"
NATURAL_FAMILY = True


OEIS = "A007770"

ALIASES = [
    "Happy Integer Sequence",
]


CLOSED_FORM = False
EVALUATION_METHOD = "Digit Process"

FAMILY_TYPE = "Sequence"


TAGS = (
    "Recursive",
    "Digit",
)


TRAITS = {
    "growth": "irregular",
    "construction": "recursive",
    "domain": "integers",
}


RELATED = [
    "Integer Sequences",
]


DOMAIN = "Integers"
GROWTH = "Irregular"


MONOTONIC = None
BOUNDED = False
OSCILLATING = False
PERIODIC = False


FORMULA_TYPE = REPRESENTATION

REQUIRES_PARAMETERS = False

PARAMETER_NAMES = ()

MIN_TERMS = 5

RECOGNITION_METHOD = "Digit Transformation"
RELIABILITY = "Exact"


def is_happy(n):

    seen = set()

    while n != 1:

        if n in seen:
            return False

        seen.add(n)

        n = sum(
            int(digit) ** 2
            for digit in str(n)
        )

    return True


def recognize(sequence):

    expected = [
        n
        for n in range(1, 1000)
        if is_happy(n)
    ][:len(sequence)]

    return sequence == expected


def fit(sequence):

    if recognize(sequence):
        return {}

    return None


def evaluate(parameters, n):

    return [
        x
        for x in range(1, 1000)
        if is_happy(x)
    ][n - 1]


def formula(parameters):

    return format_formula(
        "Repeated digit-square transformation"
    )


def complexity(_):

    return 2


def explain(parameters):

    return [
        "The sequence consists of numbers whose digit-square process reaches 1.",
        "Happy numbers are defined through repeated recursive digit transformations.",
    ]


# ============================================================
# Look-and-Say Numbers
# ============================================================

from analyzers.core.formatter import format_formula


NAME = "Look-and-Say Numbers"
DESCRIPTION = "Self-describing sequence generated by reading the previous term."
REPRESENTATION = "Recursive"
CATEGORY = "Special"
SPECIFICITY = 70
PARENT = "Recursive"
NATURAL_FAMILY = True


OEIS = "A005150"

ALIASES = [
    "Conway Sequence",
    "Look and Say Sequence",
]


CLOSED_FORM = False
EVALUATION_METHOD = "Recursive Generation"

FAMILY_TYPE = "Sequence"


TAGS = (
    "Recursive",
    "Self Generating",
    "Combinatorial",
)


TRAITS = {
    "growth": "combinatorial",
    "construction": "recursive",
    "domain": "integers",
}


RELATED = [
    "Recurrence Sequences",
]


DOMAIN = "Integers"
GROWTH = "Combinatorial"


MONOTONIC = True
BOUNDED = False
OSCILLATING = False
PERIODIC = False


FORMULA_TYPE = REPRESENTATION

REQUIRES_PARAMETERS = False

PARAMETER_NAMES = ()

MIN_TERMS = 5

RECOGNITION_METHOD = "Recursive Generation"
RELIABILITY = "Exact"


def next_term(value):

    digits = str(value)

    result = ""

    count = 1

    for i in range(1, len(digits) + 1):

        if i < len(digits) and digits[i] == digits[i - 1]:

            count += 1

        else:

            result += str(count)
            result += digits[i - 1]

            count = 1

    return int(result)


def look_and_say(n):

    if n == 1:
        return 1

    value = 1

    for _ in range(2, n + 1):

        value = next_term(value)

    return value


def recognize(sequence):

    if len(sequence) < MIN_TERMS:
        return None

    for index, value in enumerate(sequence, start=1):

        if value != look_and_say(index):
            return None

    return True


def fit(sequence):

    if recognize(sequence) is not True:
        return None

    return {}


def evaluate(parameters, n):

    return look_and_say(n)


def formula(parameters):

    return format_formula(
        "read(previous term)"
    )


def complexity(_):

    return 3


def explain(parameters):

    return [
        "The sequence matches the Look-and-Say recursive generation rule.",
        "Each term is produced by describing the digits of the previous term.",
        "The sequence is generated through self-reference rather than a closed formula.",
    ]


# ============================================================
# Motzkin Numbers
# ============================================================

from analyzers.core.formatter import format_formula


NAME = "Motzkin Numbers"
DESCRIPTION = "Counts non-crossing paths and related combinatorial structures."
REPRESENTATION = "Recursive"
CATEGORY = "Combinatorial"
SPECIFICITY = 60
PARENT = "Recursive"
NATURAL_FAMILY = True


OEIS = "A001006"

ALIASES = [
    "Motzkin Sequence",
]


CLOSED_FORM = True
EVALUATION_METHOD = "Recursive Relation"

FAMILY_TYPE = "Sequence"


TAGS = (
    "Combinatorial",
    "Recursive",
)


TRAITS = {
    "growth": "combinatorial",
    "construction": "recursive",
    "domain": "integers",
}


RELATED = [
    "Catalan Numbers",
    "Bell Numbers",
]


DOMAIN = "Integers"
GROWTH = "Combinatorial"


MONOTONIC = True
BOUNDED = False
OSCILLATING = False
PERIODIC = False


FORMULA_TYPE = REPRESENTATION

REQUIRES_PARAMETERS = False

PARAMETER_NAMES = ()

MIN_TERMS = 5

RECOGNITION_METHOD = "Recursive Relation"
RELIABILITY = "Exact"


def motzkin_number(n):

    if n == 1:
        return 1

    if n == 2:
        return 1

    previous_two = 1
    previous_one = 1

    for k in range(3, n + 1):

        current = (
            ((2 * k - 1) * previous_one)
            +
            ((3 * k - 6) * previous_two)
        ) // (k + 1)

        previous_two = previous_one
        previous_one = current

    return previous_one


def recognize(sequence):

    if len(sequence) < MIN_TERMS:
        return None

    for index, value in enumerate(sequence, start=1):

        if value != motzkin_number(index):
            return None

    return True


def fit(sequence):

    if recognize(sequence) is not True:
        return None

    return {}


def evaluate(parameters, n):

    return motzkin_number(n)


def formula(parameters):

    return format_formula(
        "M(n)=((2n-1)M(n-1)+(3n-6)M(n-2))/(n+1)"
    )


def complexity(_):

    return 2


def explain(parameters):

    return [
        "The sequence matches the Motzkin recurrence.",
        "Motzkin numbers count several combinatorial structures including non-crossing paths and polygon triangulations.",
    ]


# ============================================================
# Van Eck Numbers
# ============================================================

from analyzers.core.formatter import format_formula


NAME = "Van Eck Numbers"
DESCRIPTION = "A self-referential sequence based on previous occurrence distances."
REPRESENTATION = "Recursive"
CATEGORY = "Self-Referential"
SPECIFICITY = 70
PARENT = "Recursive"
NATURAL_FAMILY = True


OEIS = "A181391"

ALIASES = [
    "Van Eck's Sequence",
]


CLOSED_FORM = False
EVALUATION_METHOD = "Recursive Generation"

FAMILY_TYPE = "Sequence"


TAGS = (
    "Recursive",
    "Self-Referential",
    "History",
    "Integer",
)


TRAITS = {
    "growth": "irregular",
    "construction": "recursive",
    "domain": "integers",
}


RELATED = [
    "Look-and-Say Numbers",
]


DOMAIN = "Integers"
GROWTH = "Irregular"


MONOTONIC = False
BOUNDED = False
OSCILLATING = False
PERIODIC = False


FORMULA_TYPE = REPRESENTATION

REQUIRES_PARAMETERS = False

PARAMETER_NAMES = ()

MIN_TERMS = 8

RECOGNITION_METHOD = "Recursive Generation"
RELIABILITY = "Exact"


def van_eck_number(n):

    sequence = [0]

    while len(sequence) < n:

        previous = sequence[-1]

        if previous not in sequence[:-1]:

            sequence.append(0)

        else:

            last_index = len(sequence) - 1

            previous_index = (
                len(sequence)
                - 1
                - sequence[-2::-1].index(previous)
            )

            sequence.append(
                last_index - previous_index
            )

    return sequence[n - 1]


def generate(length):

    if length <= 0:

        return []

    sequence = [0]

    while len(sequence) < length:

        previous = sequence[-1]

        positions = [
            i
            for i, value in enumerate(sequence[:-1])
            if value == previous
        ]

        if not positions:

            sequence.append(0)

        else:

            sequence.append(
                (len(sequence) - 1) - positions[-1]
            )

    return sequence


def recognize(sequence):

    generated = generate(len(sequence))

    return generated == sequence


def fit(sequence):

    if recognize(sequence) is not True:

        return None

    return {}


def evaluate(parameters, n):

    return generate(n)[-1]


def formula(parameters):

    return format_formula(
        "a(n)=distance since previous occurrence"
    )


def complexity(_):

    return 3


def explain(parameters):

    return [
        "The sequence matches the Van Eck self-referential generation rule.",
        "Each term depends on when the previous value last appeared.",
        "If the previous term has not appeared before, the next term is 0.",
        "Otherwise, the next term is the distance since its previous occurrence.",
    ]